class DuplicateUserError(Exception):
    """Raised when attempting to create a record with existing user_id"""
    pass
